/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.event.*;
import java.util.*;

/**
 *
 * @author VICTUS
 */
public class GuiCollectionAdvanced extends javax.swing.JFrame {
    private DefaultListModel<String> listModel;
    private JButton clearAll;
    private JButton saveToList, insertToList, saveToSet, insertToSet, saveToMap, insertToMap;
    private List<String> itemList;
    private Set<String> itemSet;
    private Map<Integer, String> itemMap;

    /**
     * Creates new form GuiCollectionAdvanced
     */
    public GuiCollectionAdvanced() {
        initComponents();
        itemList = new ArrayList<>();
        itemSet = new HashSet<>();
        itemMap = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        savetolist = new javax.swing.JButton();
        inserttolist = new javax.swing.JButton();
        savetoset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        savetomap = new javax.swing.JButton();
        inserttomap = new javax.swing.JButton();
        clearall = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabelNamaItem = new javax.swing.JLabel();
        jTextFieldNamaItem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Buku", "Meja", "Kursi", "Tas", "Pintu" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        savetolist.setText("Save to List");

        inserttolist.setText("Insert to List");

        savetoset.setText("Save to Set");

        jButton1.setText("Insert to Set");

        savetomap.setText("Save to Map");
        savetomap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetomapActionPerformed(evt);
            }
        });

        inserttomap.setText("Insert to Map");
        inserttomap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserttomapActionPerformed(evt);
            }
        });

        clearall.setText("Clear All");

        add.setText("Add");

        update.setText("Update");

        delete.setText("Delete");

        jLabelNamaItem.setText("Nama Item :");

        jTextFieldNamaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(clearall, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(savetoset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savetomap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inserttolist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savetolist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inserttomap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savetolist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inserttolist)
                        .addGap(18, 18, 18)
                        .addComponent(savetoset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(savetomap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inserttomap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNamaItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearall)
                    .addComponent(add)
                    .addComponent(update)
                    .addComponent(delete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserttomapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserttomapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserttomapActionPerformed

    private void savetomapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetomapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savetomapActionPerformed

    private void jTextFieldNamaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaItemActionPerformed

     private void addItem() {
        String item = JOptionPane.showInputDialog("Enter item:");
        if (item != null && !item.isEmpty()) {
            listModel.addElement(item);
        }
    }

    private void updateItem() {
        int selectedIndex = jListItem.getSelectedIndex();
        String item = JOptionPane.showInputDialog("Update item:", listModel.get(selectedIndex));
        if (selectedIndex != -1 && item != null && !item.isEmpty()) {
            listModel.set(selectedIndex, item);
        }
    }

    private void deleteItem() {
        int selectedIndex = jListItem.getSelectedIndex();
        if (selectedIndex != -1) {
            listModel.remove(selectedIndex);
        }
    }

    private void clearAll() {
        listModel.clear();
    }

    private void saveToList() {
        itemList.clear();
        for (int i = 0; i < listModel.getSize(); i++) {
            itemList.add(listModel.getElementAt(i));
        }
        JOptionPane.showMessageDialog(this, "Saved to List");
    }

    private void insertToList() {
        // Logic for inserting to List can be implemented here
    }

    private void saveToSet() {
        itemSet.clear();
        for (int i = 0; i < listModel.getSize(); i++) {
            itemSet.add(listModel.getElementAt(i));
        }
        JOptionPane.showMessageDialog(this, "Saved to Set");
    }

    private void insertToSet() {
        // Logic for inserting to Set can be implemented here
    }

    private void saveToMap() {
        itemMap.clear();
        for (int i = 0; i < listModel.getSize(); i++) {
            itemMap.put(i, listModel.getElementAt(i));
        }
        JOptionPane.showMessageDialog(this, "Saved to Map");
    }

    private void insertToMap() {
        // Logic for inserting to Map can be implemented here
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new GuiCollectionAdvanced().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clearall;
    private javax.swing.JButton delete;
    private javax.swing.JButton inserttolist;
    private javax.swing.JButton inserttomap;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelNamaItem;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNamaItem;
    private javax.swing.JButton savetolist;
    private javax.swing.JButton savetomap;
    private javax.swing.JButton savetoset;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
